# Generated by Django 4.2.7 on 2025-11-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property'),
        ),
    ]
